import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* Preload cell atlas assets for faster initial load */}
        <link
          rel="preload"
          as="fetch"
          href="/sprites/cell/left/atlas_512.json"
          crossOrigin="anonymous"
        />
        <link
          rel="preload"
          as="image"
          href="/sprites/cell/left/atlas_512.webp"
        />
        <link
          rel="preload"
          as="fetch"
          href="/sprites/cell/right/atlas_512.json"
          crossOrigin="anonymous"
        />
        <link
          rel="preload"
          as="image"
          href="/sprites/cell/right/atlas_512.webp"
        />
        <link
          rel="preload"
          as="fetch"
          href="/sprites/cell/up/atlas_512.json"
          crossOrigin="anonymous"
        />
        <link
          rel="preload"
          as="image"
          href="/sprites/cell/up/atlas_512.webp"
        />
        <link
          rel="preload"
          as="fetch"
          href="/sprites/cell/down/atlas_512.json"
          crossOrigin="anonymous"
        />
        <link
          rel="preload"
          as="image"
          href="/sprites/cell/down/atlas_512.webp"
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
